/**
 * Codegen: discover every Phosphor icon used via a JSX `icon="slug"` or
 * `<Icon name="slug">` literal and emit them as a generated module that
 * iconRegistry merges into its bundled set. New JSX icons register themselves
 * on `npm run build:tokens` — no manual iconRegistry edit — while staying
 * tree-shaken (only discovered icons are imported).
 *
 * Unresolved slugs (doc-comment examples, typos, dynamic names) are skipped and
 * logged, never fatal: Icon's dev warning and the stories-coverage test remain
 * the gate for genuinely-missing icons.
 */
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { resolveIconName } from "../../nextjs-app/shared/components/Icon/iconAliases";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const SSR_DIR = join(ROOT, "node_modules/@phosphor-icons/react/dist/ssr");
const OUT = join(
  ROOT,
  "nextjs-app/shared/components/Icon/iconRegistry.discovered.ts",
);
const SCAN_ROOTS = [join(ROOT, "nextjs-app"), join(ROOT, "app")];

const validPhosphorNames = new Set(
  readdirSync(SSR_DIR)
    .filter((f) => f.endsWith(".d.ts"))
    .map((f) => f.replace(/\.d\.ts$/, "")),
);
const isKnown = (name: string) => validPhosphorNames.has(name);

function walk(dir: string, out: string[]): void {
  for (const entry of readdirSync(dir)) {
    if (entry === "node_modules" || entry === ".next" || entry === "dist")
      continue;
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) walk(full, out);
    else if (/\.(tsx|ts)$/.test(entry)) out.push(full);
  }
}

const ICON_PROP_RE = /\bicon="([a-z][a-zA-Z0-9-]*)"/g;
const ICON_NAME_RE = /<Icon\b[^>]*?\bname="([a-z][a-zA-Z0-9-]*)"/g;

const files: string[] = [];
for (const r of SCAN_ROOTS) walk(r, files);

const slugToFile = new Map<string, string>();
for (const file of files) {
  const text = readFileSync(file, "utf8");
  for (const re of [ICON_PROP_RE, ICON_NAME_RE]) {
    re.lastIndex = 0;
    let m: RegExpExecArray | null;
    while ((m = re.exec(text)) !== null) {
      if (!slugToFile.has(m[1]))
        slugToFile.set(m[1], relative(ROOT, file).replace(/\\/g, "/"));
    }
  }
}

const resolved = new Set<string>();
const skipped: string[] = [];
for (const [slug, file] of slugToFile) {
  const name = resolveIconName(slug, isKnown);
  if (name) resolved.add(name);
  else skipped.push(`${slug} (${file})`);
}

const names = [...resolved].sort();
const importBlock = names.map((n) => `  ${n},`).join("\n");
const content = `// AUTO-GENERATED by scripts/design-system/build-icon-registry.ts — do not edit.
// Phosphor icons discovered in JSX icon="…" / <Icon name="…"> literals across
// nextjs-app + app. Merged into iconRegistry's bundled set so JSX icons
// register themselves without a manual edit. Run \`npm run build:icons\`.
import {
${importBlock}
} from "@phosphor-icons/react/ssr";

export const DISCOVERED_ICONS = {
${importBlock}
} as const;
`;
writeFileSync(OUT, content);

console.log(
  `build-icon-registry: ${names.length} icons discovered from ${slugToFile.size} JSX slugs across ${files.length} files`,
);
if (skipped.length) {
  console.log(
    `build-icon-registry: ${skipped.length} slug(s) not resolvable to a Phosphor icon (skipped — dynamic/doc/typo):\n  ${skipped
      .sort()
      .join("\n  ")}`,
  );
}
