const stringProp = (name, sourceProp = name, description = "") => ({
  name,
  sourceProp,
  type: "string",
  description,
});
const numberProp = (name, sourceProp = name, description = "") => ({
  name,
  sourceProp,
  type: "number",
  description,
});
const booleanProp = (name, sourceProp = name, description = "") => ({
  name,
  sourceProp,
  type: "boolean",
  description,
});
const nativeProp = (name, type, description = "") => ({
  name,
  sourceProp: null,
  type,
  description,
});
const storyParity = ({ equivalents = [], exclusions = [] } = {}) => ({
  equivalents,
  exclusions,
});

export default [
  {
    tagName: "dt-button",
    adapterClassName: "DtButtonReactElement",
    sourceComponent: "Button",
    contract: "Button",
    defaultBackend: "native",
    nativeClassName: "DtButtonElement",
    description: "Digitaltableteur action or link control.",
    storyParity: storyParity({
      exclusions: [
        {
          react: "Async Action",
          reason:
            "React-only promise callback orchestration; native hosts own async state and set loading explicitly.",
        },
        {
          react: "Cta Bands",
          reason:
            "Marketing-site React composition rather than a reusable Button capability.",
        },
        {
          react: "Home Hero Band",
          reason:
            "Marketing-site React composition rather than a reusable Button capability.",
        },
      ],
    }),
    props: [
      stringProp("label", "children", "Visible button label."),
      stringProp("variant"),
      stringProp("tone"),
      stringProp("size"),
      stringProp("surface"),
      booleanProp("disabled"),
      booleanProp("loading"),
      booleanProp("rounded"),
      stringProp("icon"),
      stringProp("endIcon"),
      stringProp("accessibleName"),
      stringProp("accessibleNameRef"),
      stringProp("accessibleDescription"),
      stringProp("tooltip"),
      stringProp("href"),
      stringProp("target"),
      stringProp("rel"),
      booleanProp("submits"),
    ],
    events: [],
  },
  {
    tagName: "dt-badge",
    adapterClassName: "DtBadgeReactElement",
    sourceComponent: "Badge",
    contract: "Badge",
    defaultBackend: "native",
    nativeClassName: "DtBadgeElement",
    description: "Compact status label with semantic tone.",
    storyParity: storyParity({
      exclusions: [
        {
          react: "In Button End Slot",
          reason:
            "React-node composition demo; native hosts compose separate custom elements without a React end-slot prop.",
        },
      ],
    }),
    props: [
      stringProp("label", "children", "Visible badge label."),
      stringProp("variant"),
      stringProp("tone"),
      stringProp("size"),
      booleanProp("removable"),
      booleanProp("dot"),
      booleanProp("square"),
      stringProp("role"),
      nativeProp("icon", "string", "Leading native icon name."),
    ],
    events: [
      {
        callbackProp: "onRemove",
        name: "remove",
        description: "Dispatched after a removable badge is dismissed.",
      },
    ],
  },
  {
    tagName: "dt-icon-button",
    sourceComponent: "IconButton",
    contract: "IconButton",
    defaultBackend: "native",
    nativeClassName: "DtIconButtonElement",
    description: "Accessible icon-only action composed from native Button.",
    storyParity: storyParity({
      equivalents: [
        { react: "Example (site header toolbar)", native: "Example" },
      ],
    }),
    props: [
      stringProp("icon"),
      stringProp("label"),
      stringProp("variant"),
      stringProp("tone"),
      stringProp("surface"),
      stringProp("size"),
      stringProp("tooltip"),
      nativeProp("disabled", "boolean"),
      nativeProp("loading", "boolean"),
      nativeProp("submits", "boolean"),
    ],
    events: [],
  },
  {
    tagName: "dt-button-group",
    sourceComponent: "ButtonGroup",
    contract: "ButtonGroup",
    defaultBackend: "native",
    nativeClassName: "DtButtonGroupElement",
    description: "Attached or spaced group of related action controls.",
    storyParity: storyParity(),
    props: [stringProp("ariaLabel"), booleanProp("attached")],
    events: [],
  },
  {
    tagName: "dt-filter-chip",
    sourceComponent: "FilterChip",
    contract: "FilterChip",
    defaultBackend: "native",
    nativeClassName: "DtFilterChipElement",
    description: "Controlled filter toggle with pressed semantics.",
    storyParity: storyParity({
      equivalents: [{ react: "Example (filter group)", native: "Example" }],
    }),
    props: [
      stringProp("label", "children", "Visible chip label."),
      booleanProp("pressed"),
      stringProp("variant"),
      stringProp("size"),
      numberProp("count"),
      nativeProp("disabled", "boolean"),
    ],
    events: [],
  },
  {
    tagName: "dt-link",
    sourceComponent: "Link",
    contract: "Link",
    defaultBackend: "native",
    nativeClassName: "DtLinkElement",
    description: "Protocol-safe native anchor with external-link affordance.",
    storyParity: storyParity(),
    props: [
      nativeProp("href", "string"),
      nativeProp("label", "string", "Visible link label."),
      stringProp("size"),
      stringProp("underline"),
      nativeProp("target", "string"),
      nativeProp("rel", "string"),
      nativeProp("download", "string"),
      nativeProp("hrefLang", "string"),
      nativeProp("referrerPolicy", "string"),
      nativeProp("ariaCurrent", "string"),
      nativeProp("ariaLabel", "string"),
    ],
    events: [],
  },
  {
    tagName: "dt-nav-link",
    sourceComponent: "NavLink",
    contract: "NavLink",
    defaultBackend: "native",
    nativeClassName: "DtNavLinkElement",
    description: "Host-routed navigation link with boundary-safe active state.",
    storyParity: storyParity(),
    props: [
      stringProp("href"),
      stringProp("label", "children", "Visible navigation label."),
      nativeProp(
        "currentPath",
        "string",
        "Current host route used to derive active state.",
      ),
      booleanProp("exact"),
      nativeProp("size", "string"),
      nativeProp("underline", "string"),
    ],
    events: [],
  },
  {
    tagName: "dt-skip-link",
    sourceComponent: "SkipLink",
    contract: "SkipLink",
    defaultBackend: "native",
    nativeClassName: "DtSkipLinkElement",
    description: "Keyboard bypass link revealed on focus.",
    storyParity: storyParity(),
    props: [
      stringProp("href"),
      stringProp("label", "children", "Visible link label on focus."),
    ],
    events: [],
  },
  {
    tagName: "dt-spinner",
    adapterClassName: "DtSpinnerReactElement",
    sourceComponent: "Spinner",
    contract: "Spinner",
    defaultBackend: "native",
    nativeClassName: "DtSpinnerElement",
    description: "Indeterminate loading indicator.",
    storyParity: storyParity(),
    props: [stringProp("label"), stringProp("size")],
    events: [],
  },
  {
    tagName: "dt-progress",
    adapterClassName: "DtProgressReactElement",
    sourceComponent: "Progress",
    contract: "Progress",
    defaultBackend: "native",
    nativeClassName: "DtProgressElement",
    description: "Linear determinate or indeterminate progress indicator.",
    storyParity: storyParity(),
    props: [
      numberProp("value"),
      numberProp("max"),
      stringProp("label"),
      stringProp("size"),
      stringProp("state"),
      booleanProp("indeterminate"),
    ],
    events: [],
  },
  {
    tagName: "dt-status-dot",
    sourceComponent: "StatusDot",
    contract: "StatusDot",
    defaultBackend: "native",
    nativeClassName: "DtStatusDotElement",
    description:
      "Inline semantic status indicator with visible or screen-reader label.",
    storyParity: storyParity(),
    props: [
      stringProp("tone"),
      stringProp("size"),
      booleanProp("pulse"),
      stringProp("label"),
    ],
    events: [],
  },
  {
    tagName: "dt-divider",
    sourceComponent: "Divider",
    contract: "Divider",
    defaultBackend: "native",
    nativeClassName: "DtDividerElement",
    description: "Decorative or semantic horizontal and vertical separator.",
    storyParity: storyParity(),
    props: [stringProp("orientation"), booleanProp("decorative")],
    events: [],
  },
  {
    tagName: "dt-icon",
    sourceComponent: "Icon",
    contract: "Icon",
    defaultBackend: "native",
    nativeClassName: "DtIconElement",
    description:
      "Framework-free Phosphor icon with design-system sizing and motion.",
    storyParity: storyParity({
      exclusions: [
        {
          react: "Brand Icon",
          reason:
            "React brand-asset node injection is outside the raw Phosphor icon registry contract.",
        },
      ],
    }),
    props: [
      stringProp("name"),
      stringProp("weight"),
      stringProp("legacyStyle"),
      stringProp("size"),
      stringProp("color"),
      numberProp("rotate"),
      stringProp("flip"),
      booleanProp("spin"),
      booleanProp("pulse"),
      booleanProp("mirrored"),
      stringProp("ariaLabel"),
      booleanProp("decorative"),
    ],
    events: [],
  },
  {
    tagName: "dt-alert-banner",
    sourceComponent: "AlertBanner",
    contract: "AlertBanner",
    defaultBackend: "native",
    nativeClassName: "DtAlertBannerElement",
    description:
      "Persistent semantic alert with title, description, action, and dismiss slots.",
    storyParity: storyParity(),
    props: [
      stringProp("tone"),
      stringProp("titleText", "title"),
      stringProp("description"),
      booleanProp("showIcon"),
      booleanProp("dismissible"),
      stringProp("ariaLive", "aria-live"),
    ],
    events: [
      {
        callbackProp: "onDismiss",
        name: "dismiss",
        description: "Dispatched when the dismiss control is activated.",
      },
    ],
  },
  {
    tagName: "dt-empty-state",
    sourceComponent: "EmptyState",
    contract: "EmptyState",
    defaultBackend: "native",
    nativeClassName: "DtEmptyStateElement",
    description:
      "Empty-result composition with semantic heading, description, icon, and action slots.",
    storyParity: storyParity(),
    props: [
      stringProp("icon"),
      stringProp("titleText", "title"),
      stringProp("description"),
      stringProp("headingLevel"),
      stringProp("size"),
    ],
    events: [],
  },
  {
    tagName: "dt-text-input",
    sourceComponent: "TextInput",
    contract: "TextInput",
    defaultBackend: "native",
    nativeClassName: "DtTextInputElement",
    description:
      "Form-associated single-line field with native validation, label, and messages.",
    storyParity: storyParity(),
    props: [
      stringProp("label"),
      stringProp("type"),
      stringProp("size"),
      stringProp("value"),
      stringProp("defaultValue"),
      stringProp("error"),
      stringProp("helperText"),
      booleanProp("disabled"),
      booleanProp("clearable"),
      booleanProp("hideLabel"),
      nativeProp("required", "boolean"),
      nativeProp("placeholder", "string"),
      nativeProp("name", "string"),
    ],
    events: [
      {
        callbackProp: "onValueChange",
        name: "value-change",
        description: "Dispatched with detail.value after user input.",
      },
      {
        callbackProp: "onClear",
        name: "clear",
        description: "Dispatched after the clear control resets the field.",
      },
    ],
  },
  {
    tagName: "dt-text-area",
    sourceComponent: "TextArea",
    contract: "TextArea",
    defaultBackend: "native",
    nativeClassName: "DtTextAreaElement",
    description:
      "Form-associated multiline field with bounded auto-grow and messages.",
    storyParity: storyParity(),
    props: [
      stringProp("label"),
      stringProp("value"),
      stringProp("error"),
      stringProp("helperText"),
      booleanProp("animateResize"),
      numberProp("minRows"),
      numberProp("maxRows"),
      nativeProp("defaultValue", "string"),
      nativeProp("disabled", "boolean"),
      nativeProp("required", "boolean"),
      nativeProp("placeholder", "string"),
      nativeProp("name", "string"),
    ],
    events: [
      {
        callbackProp: "onChange",
        name: "value-change",
        description: "Dispatched with detail.value after user input.",
      },
    ],
  },
  {
    tagName: "dt-checkbox",
    sourceComponent: "Checkbox",
    contract: "Checkbox",
    defaultBackend: "native",
    nativeClassName: "DtCheckboxElement",
    description:
      "Form-associated checkbox with indeterminate, validation, and messaging states.",
    storyParity: storyParity({
      exclusions: [
        {
          react: "Z Checkbox Compliance",
          reason:
            "React-only internal compliance fixture; native behavior is enforced by the web-component DoD and browser tests.",
        },
      ],
    }),
    props: [
      stringProp("label"),
      booleanProp("showLabel"),
      booleanProp("checked"),
      booleanProp("indeterminate"),
      booleanProp("disabled"),
      booleanProp("defaultChecked"),
      stringProp("size"),
      stringProp("error"),
      stringProp("helperText"),
      nativeProp("required", "boolean"),
      nativeProp("name", "string"),
      nativeProp("value", "string"),
    ],
    events: [
      {
        callbackProp: "onCheckedChange",
        name: "checked-change",
        description: "Dispatched with detail.checked after user activation.",
      },
    ],
  },
  {
    tagName: "dt-switch",
    sourceComponent: "Switch",
    contract: "Switch",
    defaultBackend: "native",
    nativeClassName: "DtSwitchElement",
    description:
      "Immediate-action switch with loading, placement, and message states.",
    storyParity: storyParity({
      exclusions: [
        {
          react: "Z Switch Compliance",
          reason:
            "React-only internal compliance fixture; native behavior is enforced by the web-component DoD and browser tests.",
        },
      ],
    }),
    props: [
      booleanProp("checked"),
      booleanProp("defaultChecked"),
      booleanProp("disabled"),
      booleanProp("loading"),
      stringProp("size"),
      stringProp("label"),
      stringProp("labelPlacement"),
      stringProp("helperText"),
      stringProp("error"),
    ],
    events: [
      {
        callbackProp: "onCheckedChange",
        name: "checked-change",
        description: "Dispatched with detail.checked after user activation.",
      },
    ],
  },
];
