const stringProp = (name, sourceProp = name, description = "") => ({
  name,
  sourceProp,
  type: "string",
  description,
});
const numberProp = (name, sourceProp = name, description = "") => ({
  name,
  sourceProp,
  type: "number",
  description,
});
const booleanProp = (name, sourceProp = name, description = "") => ({
  name,
  sourceProp,
  type: "boolean",
  description,
});

export default [
  {
    tagName: "dt-button",
    adapterClassName: "DtButtonReactElement",
    sourceComponent: "Button",
    contract: "Button",
    defaultBackend: "native",
    nativeClassName: "DtButtonElement",
    description: "Digitaltableteur action or link control.",
    props: [
      stringProp("label", "children", "Visible button label."),
      stringProp("variant"),
      stringProp("tone"),
      stringProp("size"),
      stringProp("surface"),
      booleanProp("disabled"),
      booleanProp("loading"),
      booleanProp("rounded"),
      stringProp("icon"),
      stringProp("endIcon"),
      stringProp("accessibleName"),
      stringProp("accessibleNameRef"),
      stringProp("accessibleDescription"),
      stringProp("tooltip"),
      stringProp("href"),
      stringProp("target"),
      stringProp("rel"),
      booleanProp("submits"),
    ],
    events: [],
  },
  {
    tagName: "dt-badge",
    adapterClassName: "DtBadgeReactElement",
    sourceComponent: "Badge",
    contract: "Badge",
    defaultBackend: "native",
    nativeClassName: "DtBadgeElement",
    description: "Compact status label with semantic tone.",
    props: [
      stringProp("label", "children", "Visible badge label."),
      stringProp("variant"),
      stringProp("tone"),
      stringProp("size"),
      booleanProp("removable"),
      booleanProp("dot"),
      booleanProp("square"),
      stringProp("role"),
    ],
    events: [
      {
        callbackProp: "onRemove",
        name: "remove",
        description: "Dispatched after a removable badge is dismissed.",
      },
    ],
  },
  {
    tagName: "dt-spinner",
    adapterClassName: "DtSpinnerReactElement",
    sourceComponent: "Spinner",
    contract: "Spinner",
    defaultBackend: "native",
    nativeClassName: "DtSpinnerElement",
    description: "Indeterminate loading indicator.",
    props: [stringProp("label"), stringProp("size")],
    events: [],
  },
  {
    tagName: "dt-progress",
    adapterClassName: "DtProgressReactElement",
    sourceComponent: "Progress",
    contract: "Progress",
    defaultBackend: "native",
    nativeClassName: "DtProgressElement",
    description: "Linear determinate or indeterminate progress indicator.",
    props: [
      numberProp("value"),
      numberProp("max"),
      stringProp("label"),
      stringProp("size"),
      stringProp("state"),
      booleanProp("indeterminate"),
    ],
    events: [],
  },
  {
    tagName: "dt-status-dot",
    sourceComponent: "StatusDot",
    contract: "StatusDot",
    defaultBackend: "native",
    nativeClassName: "DtStatusDotElement",
    description:
      "Inline semantic status indicator with visible or screen-reader label.",
    props: [
      stringProp("tone"),
      stringProp("size"),
      booleanProp("pulse"),
      stringProp("label"),
    ],
    events: [],
  },
  {
    tagName: "dt-divider",
    sourceComponent: "Divider",
    contract: "Divider",
    defaultBackend: "native",
    nativeClassName: "DtDividerElement",
    description: "Decorative or semantic horizontal and vertical separator.",
    props: [stringProp("orientation"), booleanProp("decorative")],
    events: [],
  },
  {
    tagName: "dt-icon",
    sourceComponent: "Icon",
    contract: "Icon",
    defaultBackend: "native",
    nativeClassName: "DtIconElement",
    description:
      "Framework-free Phosphor icon with design-system sizing and motion.",
    props: [
      stringProp("name"),
      stringProp("weight"),
      stringProp("legacyStyle"),
      stringProp("size"),
      stringProp("color"),
      numberProp("rotate"),
      stringProp("flip"),
      booleanProp("spin"),
      booleanProp("pulse"),
      booleanProp("mirrored"),
      stringProp("ariaLabel"),
      booleanProp("decorative"),
    ],
    events: [],
  },
  {
    tagName: "dt-alert-banner",
    sourceComponent: "AlertBanner",
    contract: "AlertBanner",
    defaultBackend: "native",
    nativeClassName: "DtAlertBannerElement",
    description:
      "Persistent semantic alert with title, description, action, and dismiss slots.",
    props: [
      stringProp("tone"),
      stringProp("titleText", "title"),
      stringProp("description"),
      booleanProp("showIcon"),
      booleanProp("dismissible"),
      stringProp("ariaLive", "aria-live"),
    ],
    events: [
      {
        callbackProp: "onDismiss",
        name: "dismiss",
        description: "Dispatched when the dismiss control is activated.",
      },
    ],
  },
];
