// Auto-generated by scripts/update-post-metadata.ts. Do not edit manually.
export type BlogPostMeta = {
  slug: string;
  title: string;
  excerpt?: string;
  readTime?: string;
  publishedAt?: string;
  seoTitle?: string;
  seoDescription?: string;
  legacyUrl?: string;
  authorName?: string;
  authorSlug?: string;
  mainImageUrl?: string;
  mainImageAlt?: string;
  mainImageCaption?: string;
};

export const posts: BlogPostMeta[] = [
  {
    title: "Branding Design Systems",
    slug: "branding-design-systems-essay",
    excerpt: "Branding a design system transforms it from invisible infrastructure into a living language that communicates values, builds trust, and makes every interaction feel intentional, human, and unmistakably coherent.",
    readTime: "3 min read",
    publishedAt: "2025-11-26T18:43:00.000Z",
    authorName: "Petri Lahdelma",
    authorSlug: "petri-lahdelma",
  },
  {
    title: "Design System Meets AI: Building the Self-Evolving Component Library Pt 2",
    slug: "design-system-meets-ai-building-the-self-evolving-component-library-pt-2",
    excerpt: "Part 2 of a 5-part series exploring how design systems transform in the age of AI.",
    readTime: "4 min read",
    publishedAt: "2025-11-23T04:38:00.000Z",
    authorName: "Petri Lahdelma",
    authorSlug: "petri-lahdelma",
  },
  {
    title: "Design System Meets AI: Building the Self-Evolving Component Library Pt 1",
    slug: "design-system-meets-ai-building-the-self-evolving-component-library-pt-1",
    excerpt: "Part 1 of a 5-part series exploring how design systems transform in the age of AI.",
    readTime: "4 min read",
    publishedAt: "2025-11-20T22:08:00.000Z",
    authorName: "Petri Lahdelma",
    authorSlug: "petri-lahdelma",
  },
  {
    title: "Petri Lahdelma: A Biography",
    slug: "petri-lahdelma-bio",
    excerpt: "From Varissuo to leading global design systems.",
    readTime: "2 min read",
    publishedAt: "2025-06-15T00:00:00.000Z",
    authorName: "Petri Lahdelma",
    authorSlug: "petri-lahdelma",
  },
  {
    title: "Digital Craftsmanship",
    slug: "digital-craftsmanship",
    excerpt: "Thoughts on maintaining quality in a hurry-up culture.",
    readTime: "4 min read",
    publishedAt: "2025-06-10T00:00:00.000Z",
    authorName: "Petri Lahdelma",
    authorSlug: "petri-lahdelma",
  },
  {
    title: "MCP, Design Systems, and Generative UI",
    slug: "figma-mcp-design-systems",
    excerpt: "How Figma's MCP server speeds up design-to-code workflows.",
    readTime: "4 min read",
    publishedAt: "2025-06-05T00:00:00.000Z",
    authorName: "Petri Lahdelma",
    authorSlug: "petri-lahdelma",
  },
  {
    title: "Workflow Tips",
    slug: "workflow-tips",
    excerpt: "A behind-the-scenes look at how we keep projects moving.",
    readTime: "3 min read",
    publishedAt: "2025-05-12T00:00:00.000Z",
    authorName: "Petri Lahdelma",
    authorSlug: "petri-lahdelma",
  },
  {
    title: "Digitaltableteur Field Notes: In Search of Impact",
    slug: "in-search-of-impact",
    excerpt: "How a solo studio delivers enterprise-scale outcomes with boutique precision.",
    readTime: "4 min read",
    publishedAt: "2025-02-11T00:00:00.000Z",
    authorName: "Petri Lahdelma",
    authorSlug: "petri-lahdelma",
  },
  {
    title: "Designing in 2025",
    slug: "designing-in-2025",
    excerpt: "Navigating the AI-assisted creative landscape.",
    readTime: "3 min read",
    publishedAt: "2025-02-09T00:00:00.000Z",
    authorName: "Petri Lahdelma",
    authorSlug: "petri-lahdelma",
  },
  {
    title: "Thoughts on Future Branding",
    slug: "thoughts-on-future-branding",
    excerpt: "Exploring branding in the age of AI and exponential design.",
    readTime: "4 min read",
    publishedAt: "2018-06-07T00:00:00.000Z",
    authorName: "Petri Lahdelma",
    authorSlug: "petri-lahdelma",
  }
];

export const getPostMetaBySlug = (slug?: string | null) =>
  slug ? posts.find((post) => post.slug === slug) : undefined;
