// AUTO-GENERATED by scripts/generate-codeblock-fixtures.mjs
// Do not edit manually.

export type CodeBlockFixtureNode =
  | string
  | {
      readonly type: "element";
      readonly tagName: string;
      readonly properties?: Readonly<Record<string, unknown>>;
      readonly children?: readonly CodeBlockFixtureNode[];
    };

export type CodeBlockFixture = {
  readonly language: string;
  readonly code: string;
  readonly pre: CodeBlockFixtureNode;
};

export const codeBlockFixtures = {
  "tsx": {
    "language": "tsx",
    "code": "type Props = {\n  label: string;\n};\n\nexport function DemoButton({ label }: Props) {\n  return (\n    <button type=\"button\" aria-label={label}>\n      {label}\n    </button>\n  );\n}",
    "pre": {
      "type": "element",
      "tagName": "pre",
      "properties": {
        "className": [
          "shiki",
          "shiki-themes",
          "github-light-high-contrast",
          "github-dark",
          "github-light-high-contrast",
          "github-dark-high-contrast"
        ],
        "tabIndex": 0
      },
      "children": [
        {
          "type": "element",
          "tagName": "code",
          "properties": {},
          "children": [
            {
              "type": "element",
              "tagName": "span",
              "properties": {
                "data-line": ""
              },
              "children": [
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#A0111F;--shiki-dark:#F97583;--shiki-hcw:#A0111F;--shiki-hcb:#FF9492"
                  },
                  "children": [
                    "type"
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#702C00;--shiki-dark:#B392F0;--shiki-hcw:#702C00;--shiki-hcb:#FFB757"
                  },
                  "children": [
                    " Props"
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#A0111F;--shiki-dark:#F97583;--shiki-hcw:#A0111F;--shiki-hcb:#FF9492"
                  },
                  "children": [
                    " ="
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#0E1116;--shiki-dark:#E1E4E8;--shiki-hcw:#0E1116;--shiki-hcb:#F0F3F6"
                  },
                  "children": [
                    " {"
                  ]
                }
              ]
            },
            "\n",
            {
              "type": "element",
              "tagName": "span",
              "properties": {
                "data-line": ""
              },
              "children": [
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#702C00;--shiki-dark:#FFAB70;--shiki-hcw:#702C00;--shiki-hcb:#FFB757"
                  },
                  "children": [
                    "  label"
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#A0111F;--shiki-dark:#F97583;--shiki-hcw:#A0111F;--shiki-hcb:#FF9492"
                  },
                  "children": [
                    ":"
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#023B95;--shiki-dark:#79B8FF;--shiki-hcw:#023B95;--shiki-hcb:#91CBFF"
                  },
                  "children": [
                    " string"
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#0E1116;--shiki-dark:#E1E4E8;--shiki-hcw:#0E1116;--shiki-hcb:#F0F3F6"
                  },
                  "children": [
                    ";"
                  ]
                }
              ]
            },
            "\n",
            {
              "type": "element",
              "tagName": "span",
              "properties": {
                "data-line": ""
              },
              "children": [
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#0E1116;--shiki-dark:#E1E4E8;--shiki-hcw:#0E1116;--shiki-hcb:#F0F3F6"
                  },
                  "children": [
                    "};"
                  ]
                }
              ]
            },
            "\n",
            {
              "type": "element",
              "tagName": "span",
              "properties": {
                "data-line": ""
              },
              "children": []
            },
            "\n",
            {
              "type": "element",
              "tagName": "span",
              "properties": {
                "data-line": ""
              },
              "children": [
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#A0111F;--shiki-dark:#F97583;--shiki-hcw:#A0111F;--shiki-hcb:#FF9492"
                  },
                  "children": [
                    "export"
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#A0111F;--shiki-dark:#F97583;--shiki-hcw:#A0111F;--shiki-hcb:#FF9492"
                  },
                  "children": [
                    " function"
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#622CBC;--shiki-dark:#B392F0;--shiki-hcw:#622CBC;--shiki-hcb:#DBB7FF"
                  },
                  "children": [
                    " DemoButton"
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#0E1116;--shiki-dark:#E1E4E8;--shiki-hcw:#0E1116;--shiki-hcb:#F0F3F6"
                  },
                  "children": [
                    "({ "
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#702C00;--shiki-dark:#FFAB70;--shiki-hcw:#702C00;--shiki-hcb:#FFB757"
                  },
                  "children": [
                    "label"
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#0E1116;--shiki-dark:#E1E4E8;--shiki-hcw:#0E1116;--shiki-hcb:#F0F3F6"
                  },
                  "children": [
                    " }"
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#A0111F;--shiki-dark:#F97583;--shiki-hcw:#A0111F;--shiki-hcb:#FF9492"
                  },
                  "children": [
                    ":"
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#702C00;--shiki-dark:#B392F0;--shiki-hcw:#702C00;--shiki-hcb:#FFB757"
                  },
                  "children": [
                    " Props"
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#0E1116;--shiki-dark:#E1E4E8;--shiki-hcw:#0E1116;--shiki-hcb:#F0F3F6"
                  },
                  "children": [
                    ") {"
                  ]
                }
              ]
            },
            "\n",
            {
              "type": "element",
              "tagName": "span",
              "properties": {
                "data-line": ""
              },
              "children": [
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#A0111F;--shiki-dark:#F97583;--shiki-hcw:#A0111F;--shiki-hcb:#FF9492"
                  },
                  "children": [
                    "  return"
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#0E1116;--shiki-dark:#E1E4E8;--shiki-hcw:#0E1116;--shiki-hcb:#F0F3F6"
                  },
                  "children": [
                    " ("
                  ]
                }
              ]
            },
            "\n",
            {
              "type": "element",
              "tagName": "span",
              "properties": {
                "data-line": ""
              },
              "children": [
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#0E1116;--shiki-dark:#E1E4E8;--shiki-hcw:#0E1116;--shiki-hcb:#F0F3F6"
                  },
                  "children": [
                    "    <"
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#024C1A;--shiki-dark:#85E89D;--shiki-hcw:#024C1A;--shiki-hcb:#72F088"
                  },
                  "children": [
                    "button"
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#023B95;--shiki-dark:#B392F0;--shiki-hcw:#023B95;--shiki-hcb:#91CBFF"
                  },
                  "children": [
                    " type"
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#A0111F;--shiki-dark:#F97583;--shiki-hcw:#A0111F;--shiki-hcb:#FF9492"
                  },
                  "children": [
                    "="
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#032563;--shiki-dark:#9ECBFF;--shiki-hcw:#032563;--shiki-hcb:#ADDCFF"
                  },
                  "children": [
                    "\"button\""
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#023B95;--shiki-dark:#B392F0;--shiki-hcw:#023B95;--shiki-hcb:#91CBFF"
                  },
                  "children": [
                    " aria-label"
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#A0111F;--shiki-dark:#F97583;--shiki-hcw:#A0111F;--shiki-hcb:#FF9492"
                  },
                  "children": [
                    "="
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#A0111F;--shiki-dark:#E1E4E8;--shiki-hcw:#A0111F;--shiki-hcb:#FF9492"
                  },
                  "children": [
                    "{"
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#0E1116;--shiki-dark:#E1E4E8;--shiki-hcw:#0E1116;--shiki-hcb:#F0F3F6"
                  },
                  "children": [
                    "label"
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#A0111F;--shiki-dark:#E1E4E8;--shiki-hcw:#A0111F;--shiki-hcb:#FF9492"
                  },
                  "children": [
                    "}"
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#0E1116;--shiki-dark:#E1E4E8;--shiki-hcw:#0E1116;--shiki-hcb:#F0F3F6"
                  },
                  "children": [
                    ">"
                  ]
                }
              ]
            },
            "\n",
            {
              "type": "element",
              "tagName": "span",
              "properties": {
                "data-line": ""
              },
              "children": [
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#A0111F;--shiki-dark:#E1E4E8;--shiki-hcw:#A0111F;--shiki-hcb:#FF9492"
                  },
                  "children": [
                    "      {"
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#0E1116;--shiki-dark:#E1E4E8;--shiki-hcw:#0E1116;--shiki-hcb:#F0F3F6"
                  },
                  "children": [
                    "label"
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#A0111F;--shiki-dark:#E1E4E8;--shiki-hcw:#A0111F;--shiki-hcb:#FF9492"
                  },
                  "children": [
                    "}"
                  ]
                }
              ]
            },
            "\n",
            {
              "type": "element",
              "tagName": "span",
              "properties": {
                "data-line": ""
              },
              "children": [
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#0E1116;--shiki-dark:#E1E4E8;--shiki-hcw:#0E1116;--shiki-hcb:#F0F3F6"
                  },
                  "children": [
                    "    </"
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#024C1A;--shiki-dark:#85E89D;--shiki-hcw:#024C1A;--shiki-hcb:#72F088"
                  },
                  "children": [
                    "button"
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#0E1116;--shiki-dark:#E1E4E8;--shiki-hcw:#0E1116;--shiki-hcb:#F0F3F6"
                  },
                  "children": [
                    ">"
                  ]
                }
              ]
            },
            "\n",
            {
              "type": "element",
              "tagName": "span",
              "properties": {
                "data-line": ""
              },
              "children": [
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#0E1116;--shiki-dark:#E1E4E8;--shiki-hcw:#0E1116;--shiki-hcb:#F0F3F6"
                  },
                  "children": [
                    "  );"
                  ]
                }
              ]
            },
            "\n",
            {
              "type": "element",
              "tagName": "span",
              "properties": {
                "data-line": ""
              },
              "children": [
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#0E1116;--shiki-dark:#E1E4E8;--shiki-hcw:#0E1116;--shiki-hcb:#F0F3F6"
                  },
                  "children": [
                    "}"
                  ]
                }
              ]
            }
          ]
        }
      ]
    }
  },
  "bash": {
    "language": "bash",
    "code": "curl -X POST https://api.digitaltableteur.com/v1/send \\\n+  -H \"Authorization: Bearer $TOKEN\" \\\n+  -H \"Content-Type: application/json\" \\\n+  -d '{\"name\":\"Petri\",\"message\":\"Hello\"}'",
    "pre": {
      "type": "element",
      "tagName": "pre",
      "properties": {
        "className": [
          "shiki",
          "shiki-themes",
          "github-light-high-contrast",
          "github-dark",
          "github-light-high-contrast",
          "github-dark-high-contrast"
        ],
        "tabIndex": 0
      },
      "children": [
        {
          "type": "element",
          "tagName": "code",
          "properties": {},
          "children": [
            {
              "type": "element",
              "tagName": "span",
              "properties": {
                "data-line": ""
              },
              "children": [
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#702C00;--shiki-dark:#B392F0;--shiki-hcw:#702C00;--shiki-hcb:#FFB757"
                  },
                  "children": [
                    "curl"
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#023B95;--shiki-dark:#79B8FF;--shiki-hcw:#023B95;--shiki-hcb:#91CBFF"
                  },
                  "children": [
                    " -X"
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#032563;--shiki-dark:#9ECBFF;--shiki-hcw:#032563;--shiki-hcb:#ADDCFF"
                  },
                  "children": [
                    " POST"
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#032563;--shiki-dark:#9ECBFF;--shiki-hcw:#032563;--shiki-hcb:#ADDCFF"
                  },
                  "children": [
                    " https://api.digitaltableteur.com/v1/send"
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#A0111F;--shiki-dark:#79B8FF;--shiki-hcw:#A0111F;--shiki-hcb:#FF9492"
                  },
                  "children": [
                    " \\"
                  ]
                }
              ]
            },
            "\n",
            {
              "type": "element",
              "tagName": "span",
              "properties": {
                "data-line": ""
              },
              "children": [
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#0E1116;--shiki-dark:#E1E4E8;--shiki-hcw:#0E1116;--shiki-hcb:#F0F3F6"
                  },
                  "children": [
                    "+  "
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#023B95;--shiki-dark:#79B8FF;--shiki-hcw:#023B95;--shiki-hcb:#91CBFF"
                  },
                  "children": [
                    "-H"
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#032563;--shiki-dark:#9ECBFF;--shiki-hcw:#032563;--shiki-hcb:#ADDCFF"
                  },
                  "children": [
                    " \"Authorization: Bearer "
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#0E1116;--shiki-dark:#E1E4E8;--shiki-hcw:#0E1116;--shiki-hcb:#F0F3F6"
                  },
                  "children": [
                    "$TOKEN"
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#032563;--shiki-dark:#9ECBFF;--shiki-hcw:#032563;--shiki-hcb:#ADDCFF"
                  },
                  "children": [
                    "\""
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#A0111F;--shiki-dark:#79B8FF;--shiki-hcw:#A0111F;--shiki-hcb:#FF9492"
                  },
                  "children": [
                    " \\"
                  ]
                }
              ]
            },
            "\n",
            {
              "type": "element",
              "tagName": "span",
              "properties": {
                "data-line": ""
              },
              "children": [
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#0E1116;--shiki-dark:#E1E4E8;--shiki-hcw:#0E1116;--shiki-hcb:#F0F3F6"
                  },
                  "children": [
                    "+  "
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#023B95;--shiki-dark:#79B8FF;--shiki-hcw:#023B95;--shiki-hcb:#91CBFF"
                  },
                  "children": [
                    "-H"
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#032563;--shiki-dark:#9ECBFF;--shiki-hcw:#032563;--shiki-hcb:#ADDCFF"
                  },
                  "children": [
                    " \"Content-Type: application/json\""
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#A0111F;--shiki-dark:#79B8FF;--shiki-hcw:#A0111F;--shiki-hcb:#FF9492"
                  },
                  "children": [
                    " \\"
                  ]
                }
              ]
            },
            "\n",
            {
              "type": "element",
              "tagName": "span",
              "properties": {
                "data-line": ""
              },
              "children": [
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#0E1116;--shiki-dark:#E1E4E8;--shiki-hcw:#0E1116;--shiki-hcb:#F0F3F6"
                  },
                  "children": [
                    "+  "
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#023B95;--shiki-dark:#79B8FF;--shiki-hcw:#023B95;--shiki-hcb:#91CBFF"
                  },
                  "children": [
                    "-d"
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#032563;--shiki-dark:#9ECBFF;--shiki-hcw:#032563;--shiki-hcb:#ADDCFF"
                  },
                  "children": [
                    " '{\"name\":\"Petri\",\"message\":\"Hello\"}'"
                  ]
                }
              ]
            }
          ]
        }
      ]
    }
  },
  "json": {
    "language": "json",
    "code": "{\"service\":\"digitaltableteur\",\"mode\":\"active\",\"regions\":[\"eu\",\"us\"]}",
    "pre": {
      "type": "element",
      "tagName": "pre",
      "properties": {
        "className": [
          "shiki",
          "shiki-themes",
          "github-light-high-contrast",
          "github-dark",
          "github-light-high-contrast",
          "github-dark-high-contrast"
        ],
        "tabIndex": 0
      },
      "children": [
        {
          "type": "element",
          "tagName": "code",
          "properties": {},
          "children": [
            {
              "type": "element",
              "tagName": "span",
              "properties": {
                "data-line": ""
              },
              "children": [
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#0E1116;--shiki-dark:#E1E4E8;--shiki-hcw:#0E1116;--shiki-hcb:#F0F3F6"
                  },
                  "children": [
                    "{"
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#024C1A;--shiki-dark:#79B8FF;--shiki-hcw:#024C1A;--shiki-hcb:#72F088"
                  },
                  "children": [
                    "\"service\""
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#0E1116;--shiki-dark:#E1E4E8;--shiki-hcw:#0E1116;--shiki-hcb:#F0F3F6"
                  },
                  "children": [
                    ":"
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#032563;--shiki-dark:#9ECBFF;--shiki-hcw:#032563;--shiki-hcb:#ADDCFF"
                  },
                  "children": [
                    "\"digitaltableteur\""
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#0E1116;--shiki-dark:#E1E4E8;--shiki-hcw:#0E1116;--shiki-hcb:#F0F3F6"
                  },
                  "children": [
                    ","
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#024C1A;--shiki-dark:#79B8FF;--shiki-hcw:#024C1A;--shiki-hcb:#72F088"
                  },
                  "children": [
                    "\"mode\""
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#0E1116;--shiki-dark:#E1E4E8;--shiki-hcw:#0E1116;--shiki-hcb:#F0F3F6"
                  },
                  "children": [
                    ":"
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#032563;--shiki-dark:#9ECBFF;--shiki-hcw:#032563;--shiki-hcb:#ADDCFF"
                  },
                  "children": [
                    "\"active\""
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#0E1116;--shiki-dark:#E1E4E8;--shiki-hcw:#0E1116;--shiki-hcb:#F0F3F6"
                  },
                  "children": [
                    ","
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#024C1A;--shiki-dark:#79B8FF;--shiki-hcw:#024C1A;--shiki-hcb:#72F088"
                  },
                  "children": [
                    "\"regions\""
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#0E1116;--shiki-dark:#E1E4E8;--shiki-hcw:#0E1116;--shiki-hcb:#F0F3F6"
                  },
                  "children": [
                    ":["
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#032563;--shiki-dark:#9ECBFF;--shiki-hcw:#032563;--shiki-hcb:#ADDCFF"
                  },
                  "children": [
                    "\"eu\""
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#0E1116;--shiki-dark:#E1E4E8;--shiki-hcw:#0E1116;--shiki-hcb:#F0F3F6"
                  },
                  "children": [
                    ","
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#032563;--shiki-dark:#9ECBFF;--shiki-hcw:#032563;--shiki-hcb:#ADDCFF"
                  },
                  "children": [
                    "\"us\""
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#0E1116;--shiki-dark:#E1E4E8;--shiki-hcw:#0E1116;--shiki-hcb:#F0F3F6"
                  },
                  "children": [
                    "]}"
                  ]
                }
              ]
            }
          ]
        }
      ]
    }
  },
  "longLine": {
    "language": "ts",
    "code": "const longLine = 'This is an intentionally long line to verify horizontal scrolling within the code window without wrapping.';",
    "pre": {
      "type": "element",
      "tagName": "pre",
      "properties": {
        "className": [
          "shiki",
          "shiki-themes",
          "github-light-high-contrast",
          "github-dark",
          "github-light-high-contrast",
          "github-dark-high-contrast"
        ],
        "tabIndex": 0
      },
      "children": [
        {
          "type": "element",
          "tagName": "code",
          "properties": {},
          "children": [
            {
              "type": "element",
              "tagName": "span",
              "properties": {
                "data-line": ""
              },
              "children": [
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#A0111F;--shiki-dark:#F97583;--shiki-hcw:#A0111F;--shiki-hcb:#FF9492"
                  },
                  "children": [
                    "const"
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#023B95;--shiki-dark:#79B8FF;--shiki-hcw:#023B95;--shiki-hcb:#91CBFF"
                  },
                  "children": [
                    " longLine"
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#A0111F;--shiki-dark:#F97583;--shiki-hcw:#A0111F;--shiki-hcb:#FF9492"
                  },
                  "children": [
                    " ="
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#032563;--shiki-dark:#9ECBFF;--shiki-hcw:#032563;--shiki-hcb:#ADDCFF"
                  },
                  "children": [
                    " 'This is an intentionally long line to verify horizontal scrolling within the code window without wrapping.'"
                  ]
                },
                {
                  "type": "element",
                  "tagName": "span",
                  "properties": {
                    "style": "--shiki-light:#0E1116;--shiki-dark:#E1E4E8;--shiki-hcw:#0E1116;--shiki-hcb:#F0F3F6"
                  },
                  "children": [
                    ";"
                  ]
                }
              ]
            }
          ]
        }
      ]
    }
  }
} as const;
