// AUTO-GENERATED by scripts/generate-blog-manifest.mjs
// Do not edit manually.
import Post0, { frontmatter as Post0Frontmatter } from "../../../content/posts/branding-design-systems-essay.mdx"
import Post1, { frontmatter as Post1Frontmatter } from "../../../content/posts/design-system-meets-ai-building-the-self-evolving-component-library-pt-1.mdx"
import Post2, { frontmatter as Post2Frontmatter } from "../../../content/posts/design-system-meets-ai-building-the-self-evolving-component-library-pt-2.mdx"
import Post3, { frontmatter as Post3Frontmatter } from "../../../content/posts/designing-in-2025.mdx"
import Post4, { frontmatter as Post4Frontmatter } from "../../../content/posts/digital-craftsmanship.mdx"
import Post5, { frontmatter as Post5Frontmatter } from "../../../content/posts/figma-mcp-design-systems.mdx"
import Post6, { frontmatter as Post6Frontmatter } from "../../../content/posts/in-search-of-impact.mdx"
import Post7, { frontmatter as Post7Frontmatter } from "../../../content/posts/petri-lahdelma-bio.mdx"
import Post8, { frontmatter as Post8Frontmatter } from "../../../content/posts/the-evolutionary-difference-between-constructive-and-constrictive-criticism.mdx"
import Post9, { frontmatter as Post9Frontmatter } from "../../../content/posts/thoughts-on-future-branding.mdx"
import Post10, { frontmatter as Post10Frontmatter } from "../../../content/posts/workflow-tips.mdx"

export type BlogManifestEntry = {
  slug: string;
  Component: import("react").ComponentType;
  frontmatter?: {
    title?: string;
    excerpt?: string;
    readTime?: string;
    publishedAt?: string;
    seoTitle?: string;
    seoDescription?: string;
    legacyUrl?: string;
    authorName?: string;
    authorSlug?: string;
    mainImageUrl?: string;
    mainImageAlt?: string;
    mainImageCaption?: string;
  };
};

export const blogManifest: BlogManifestEntry[] = [
  { slug: "branding-design-systems-essay", Component: Post0 as unknown as import("react").ComponentType, frontmatter: Post0Frontmatter },
  { slug: "design-system-meets-ai-building-the-self-evolving-component-library-pt-1", Component: Post1 as unknown as import("react").ComponentType, frontmatter: Post1Frontmatter },
  { slug: "design-system-meets-ai-building-the-self-evolving-component-library-pt-2", Component: Post2 as unknown as import("react").ComponentType, frontmatter: Post2Frontmatter },
  { slug: "designing-in-2025", Component: Post3 as unknown as import("react").ComponentType, frontmatter: Post3Frontmatter },
  { slug: "digital-craftsmanship", Component: Post4 as unknown as import("react").ComponentType, frontmatter: Post4Frontmatter },
  { slug: "figma-mcp-design-systems", Component: Post5 as unknown as import("react").ComponentType, frontmatter: Post5Frontmatter },
  { slug: "in-search-of-impact", Component: Post6 as unknown as import("react").ComponentType, frontmatter: Post6Frontmatter },
  { slug: "petri-lahdelma-bio", Component: Post7 as unknown as import("react").ComponentType, frontmatter: Post7Frontmatter },
  { slug: "the-evolutionary-difference-between-constructive-and-constrictive-criticism", Component: Post8 as unknown as import("react").ComponentType, frontmatter: Post8Frontmatter },
  { slug: "thoughts-on-future-branding", Component: Post9 as unknown as import("react").ComponentType, frontmatter: Post9Frontmatter },
  { slug: "workflow-tips", Component: Post10 as unknown as import("react").ComponentType, frontmatter: Post10Frontmatter }
];
