import fs from "fs";
import path from "path";
import matter from "gray-matter";

type Frontmatter = {
  title?: string;
  slug?: string;
  excerpt?: string;
  readTime?: string;
  publishedAt?: string;
  modifiedAt?: string;
  seoTitle?: string;
  seoDescription?: string;
  legacyUrl?: string;
  authorName?: string;
  authorSlug?: string;
  mainImageUrl?: string;
  mainImageAlt?: string;
  mainImageCaption?: string;
  tags?: string[];
};

type PostMeta = Required<Pick<Frontmatter, "title" | "slug">> &
  Omit<Frontmatter, "title" | "slug">;

const ROOT = process.cwd();
const POSTS_DIR = path.join(ROOT, "content", "posts");
const OUTPUTS = [
  // Next.js App Router (production)
  path.join(ROOT, "app", "blog", "postMetadata.ts"),
  // Legacy Next.js folder (still referenced by some tooling/docs)
  path.join(ROOT, "nextjs-app", "app", "blog", "postMetadata.ts"),
];

const readFrontmatter = (filePath: string): PostMeta => {
  const raw = fs.readFileSync(filePath, "utf8");
  const { data } = matter(raw);
  const fm = data as Frontmatter;
  const fileSlug = path.basename(filePath).replace(/\.mdx?$/, "");
  return {
    title: fm.title ?? fileSlug,
    slug: fm.slug ?? fileSlug,
    excerpt: fm.excerpt,
    readTime: fm.readTime,
    publishedAt: fm.publishedAt,
    modifiedAt: fm.modifiedAt,
    seoTitle: fm.seoTitle,
    seoDescription: fm.seoDescription,
    legacyUrl: fm.legacyUrl,
    authorName: fm.authorName,
    authorSlug: fm.authorSlug,
    mainImageUrl: fm.mainImageUrl,
    mainImageAlt: fm.mainImageAlt,
    mainImageCaption: fm.mainImageCaption,
    tags: fm.tags,
  };
};

const formatValue = (value: unknown) => JSON.stringify(value);

const formatPost = (post: PostMeta) => {
  const entries = Object.entries(post).filter(([, value]) => value !== undefined);
  const lines = entries.map(
    ([key, value]) => `    ${key}: ${formatValue(value)},`,
  );
  return ["  {", ...lines, "  }"].join("\n");
};

const generate = () => {
  const files = fs
    .readdirSync(POSTS_DIR)
    .filter((file) => file.endsWith(".mdx"))
    .map((file) => path.join(POSTS_DIR, file));

  const posts = files.map(readFrontmatter).sort((a, b) => {
    const timeA = a.publishedAt ? new Date(a.publishedAt).getTime() : 0;
    const timeB = b.publishedAt ? new Date(b.publishedAt).getTime() : 0;
    return timeB - timeA;
  });

  const fileContent = `// Auto-generated by scripts/update-post-metadata.ts. Do not edit manually.
export type BlogPostMeta = {
  slug: string;
  title: string;
  excerpt?: string;
  readTime?: string;
  publishedAt?: string;
  modifiedAt?: string;
  seoTitle?: string;
  seoDescription?: string;
  legacyUrl?: string;
  authorName?: string;
  authorSlug?: string;
  mainImageUrl?: string;
  mainImageAlt?: string;
  mainImageCaption?: string;
  tags?: string[];
};

export const posts: BlogPostMeta[] = [
${posts.map(formatPost).join(",\n")}
];

export const getPostMetaBySlug = (slug?: string | null) =>
  slug ? posts.find((post) => post.slug === slug) : undefined;
`;

  for (const outputPath of OUTPUTS) {
    fs.writeFileSync(outputPath, fileContent, "utf8");
    console.log(
      `Wrote ${posts.length} posts to ${path.relative(ROOT, outputPath)}`,
    );
  }
};

generate();
