import fs from "fs";
import path from "path";
import matter from "gray-matter";

type Frontmatter = {
  title?: string;
  slug?: string;
  excerpt?: string;
  readTime?: string;
  publishedAt?: string;
  intendedPublishedAt?: string;
  draft?: boolean;
  status?: string;
  modifiedAt?: string;
  seoTitle?: string;
  seoDescription?: string;
  legacyUrl?: string;
  authorName?: string;
  authorSlug?: string;
  mainImageUrl?: string;
  mainImageAlt?: string;
  mainImageCaption?: string;
  tags?: string[];
};

type PostMeta = Required<Pick<Frontmatter, "title" | "slug">> &
  Omit<Frontmatter, "title" | "slug">;

const ROOT = process.cwd();
const POSTS_DIR = path.join(ROOT, "content", "posts");
const DRAFTS_DIR = path.join(ROOT, "content", "drafts");
const OUTPUTS = [
  // Next.js App Router (production)
  path.join(ROOT, "app", "blog", "postMetadata.ts"),
  // Legacy Next.js folder (still referenced by some tooling/docs)
  path.join(ROOT, "nextjs-app", "app", "blog", "postMetadata.ts"),
];

const SHOW_UNPUBLISHED_POSTS =
  process.env.SHOW_UNPUBLISHED_POSTS === "true" ||
  process.env.NEXT_PUBLIC_SHOW_UNPUBLISHED_POSTS === "true";

const isBundledPost = (post: PostMeta, kind: "post" | "draft") => {
  if (SHOW_UNPUBLISHED_POSTS) return true;
  if (post.draft || post.status === "draft" || post.status === "unpublished") {
    return false;
  }

  if (kind === "draft") {
    return post.status === "scheduled" && Boolean(post.publishedAt);
  }

  return true;
};

const readFrontmatter = (filePath: string): PostMeta => {
  const raw = fs.readFileSync(filePath, "utf8");
  const { data } = matter(raw);
  const fm = data as Frontmatter;
  const fileSlug = path.basename(filePath).replace(/\.mdx?$/, "");
  return {
    title: fm.title ?? fileSlug,
    slug: fm.slug ?? fileSlug,
    excerpt: fm.excerpt,
    readTime: fm.readTime,
    publishedAt: fm.publishedAt,
    intendedPublishedAt: fm.intendedPublishedAt,
    draft: fm.draft,
    status: fm.status,
    modifiedAt: fm.modifiedAt,
    seoTitle: fm.seoTitle,
    seoDescription: fm.seoDescription,
    legacyUrl: fm.legacyUrl,
    authorName: fm.authorName,
    authorSlug: fm.authorSlug,
    mainImageUrl: fm.mainImageUrl,
    mainImageAlt: fm.mainImageAlt,
    mainImageCaption: fm.mainImageCaption,
    tags: fm.tags,
  };
};

const formatValue = (value: unknown) => JSON.stringify(value);

const formatPost = (post: PostMeta) => {
  const entries = Object.entries(post).filter(
    ([key, value]) => value !== undefined && key !== "intendedPublishedAt",
  );
  const lines = entries.map(
    ([key, value]) => `    ${key}: ${formatValue(value)},`,
  );
  return ["  {", ...lines, "  }"].join("\n");
};

const collectPostFiles = (dir: string, kind: "post" | "draft") => {
  if (!fs.existsSync(dir)) return [];

  const files: string[] = [];
  const walk = (currentDir: string) => {
    for (const entry of fs.readdirSync(currentDir, { withFileTypes: true })) {
      const filePath = path.join(currentDir, entry.name);
      if (entry.isDirectory()) {
        walk(filePath);
        continue;
      }

      if (entry.name.endsWith(".mdx")) {
        files.push(filePath);
      }
    }
  };

  walk(dir);

  return files.map(readFrontmatter).filter((post) => isBundledPost(post, kind));
};

const generate = () => {
  const posts = [
    ...collectPostFiles(POSTS_DIR, "post"),
    ...collectPostFiles(DRAFTS_DIR, "draft"),
  ].sort((a, b) => {
    const timeA = a.publishedAt ? new Date(a.publishedAt).getTime() : 0;
    const timeB = b.publishedAt ? new Date(b.publishedAt).getTime() : 0;
    return timeB - timeA;
  });

  const fileContent = `// Auto-generated by scripts/update-post-metadata.ts. Do not edit manually.
export type BlogPostMeta = {
  slug: string;
  title: string;
  excerpt?: string;
  readTime?: string;
  publishedAt?: string;
  intendedPublishedAt?: string;
  draft?: boolean;
  status?: string;
  modifiedAt?: string;
  seoTitle?: string;
  seoDescription?: string;
  legacyUrl?: string;
  authorName?: string;
  authorSlug?: string;
  mainImageUrl?: string;
  mainImageAlt?: string;
  mainImageCaption?: string;
  tags?: string[];
};

const showUnpublishedPosts =
  process.env.SHOW_UNPUBLISHED_POSTS === "true" ||
  process.env.NEXT_PUBLIC_SHOW_UNPUBLISHED_POSTS === "true";

const isVisiblePost = (post: BlogPostMeta) => {
  if (showUnpublishedPosts) return true;
  if (post.draft || post.status === "draft" || post.status === "unpublished") {
    return false;
  }

  if (!post.publishedAt) return true;
  const publishedAt = new Date(post.publishedAt);
  return (
    Number.isNaN(publishedAt.getTime()) || publishedAt.getTime() <= Date.now()
  );
};

export const allPosts: BlogPostMeta[] = [
${posts.map(formatPost).join(",\n")}
];

export const getVisiblePosts = () => allPosts.filter(isVisiblePost);

export const getPostMetaBySlug = (slug?: string | null) =>
  slug ? getVisiblePosts().find((post) => post.slug === slug) : undefined;
`;

  for (const outputPath of OUTPUTS) {
    fs.writeFileSync(outputPath, fileContent, "utf8");
    console.log(
      `Wrote ${posts.length} posts to ${path.relative(ROOT, outputPath)}`,
    );
  }
};

generate();
