/**
 * Markdown Report Generator for Page-Level Verification
 *
 * Generates human-readable markdown reports from audit results.
 * Used to document page compliance status across theme/language matrix.
 *
 * Phase 7: Page-Level Verification
 * Plan: 07-01 (Infrastructure Setup)
 */

import type { AuditResult, AxeViolation } from "./audit-page";

/**
 * Generate a markdown report for a single page's audit results.
 *
 * Creates a structured report with:
 * - Header with page name, URL, timestamp, overall status
 * - Section per theme with language table (violations, passes, status)
 * - List of violations with HTML snippets if any exist
 *
 * @param pageName - Human-readable page name
 * @param results - Array of AuditResults for all theme/language combinations
 * @returns Markdown string
 */
export function generatePageReport(
  pageName: string,
  results: AuditResult[]
): string {
  if (results.length === 0) {
    return `# Page Verification Report: ${pageName}\n\n**Error:** No audit results provided.\n`;
  }

  // Extract unique themes and languages
  const themes = Array.from(new Set(results.map((r) => r.theme)));
  const languages = Array.from(new Set(results.map((r) => r.language)));

  // Calculate overall status
  const overallStatus = results.every((r) => r.status === "PASS")
    ? "PASS"
    : "FAIL";
  const totalViolations = results.reduce(
    (sum, r) => sum + r.violations.length,
    0
  );

  // Build the report
  let md = `# Page Verification Report: ${pageName}\n\n`;
  md += `**URL:** ${results[0].url}\n`;
  md += `**Verified:** ${new Date().toISOString()}\n`;
  md += `**Status:** ${overallStatus}\n`;
  md += `**Total Violations:** ${totalViolations}\n\n`;

  md += `## Summary\n\n`;
  md += `| Metric | Value |\n`;
  md += `|--------|-------|\n`;
  md += `| Themes Tested | ${themes.length} |\n`;
  md += `| Languages Tested | ${languages.length} |\n`;
  md += `| Total Combinations | ${results.length} |\n`;
  md += `| Passing | ${results.filter((r) => r.status === "PASS").length} |\n`;
  md += `| Failing | ${results.filter((r) => r.status === "FAIL").length} |\n\n`;

  md += `## Automated Audit (axe-core)\n\n`;

  // Section per theme
  for (const theme of themes) {
    md += `### ${theme} Theme\n\n`;
    md += `| Language | Violations | Passes | Incomplete | Status |\n`;
    md += `|----------|------------|--------|------------|--------|\n`;

    for (const lang of languages) {
      const result = results.find(
        (r) => r.theme === theme && r.language === lang
      );
      if (result) {
        md += `| ${lang.toUpperCase()} | ${result.violations.length} | ${result.passes} | ${result.incomplete} | ${result.status} |\n`;
      }
    }
    md += `\n`;
  }

  // List violations if any
  const allViolations = results.flatMap((r) =>
    r.violations.map((v) => ({
      ...v,
      theme: r.theme,
      language: r.language,
    }))
  );

  if (allViolations.length > 0) {
    md += `## Violations\n\n`;

    // Group violations by rule ID
    const violationsByRule = new Map<
      string,
      Array<AxeViolation & { theme: string; language: string }>
    >();
    for (const v of allViolations) {
      const existing = violationsByRule.get(v.id) || [];
      existing.push(v);
      violationsByRule.set(v.id, existing);
    }

    for (const [ruleId, violations] of Array.from(violationsByRule.entries())) {
      const first = violations[0];
      md += `### ${ruleId}\n\n`;
      md += `**Impact:** ${first.impact || "unknown"}\n`;
      md += `**Description:** ${first.description}\n`;
      md += `**Help:** ${first.help}\n`;
      md += `**More Info:** [${first.helpUrl}](${first.helpUrl})\n\n`;

      md += `**Affected Combinations:**\n`;
      for (const v of violations) {
        md += `- ${v.theme} / ${v.language.toUpperCase()}\n`;
      }
      md += `\n`;

      // Show first few affected elements
      const uniqueNodes = new Set<string>();
      for (const v of violations) {
        for (const node of v.nodes.slice(0, 3)) {
          uniqueNodes.add(node.target.join(" > "));
        }
      }

      if (uniqueNodes.size > 0) {
        md += `**Sample Elements:**\n\n`;
        md += "```html\n";
        let count = 0;
        for (const target of Array.from(uniqueNodes)) {
          if (count >= 5) {
            md += `<!-- ... and more -->\n`;
            break;
          }
          md += `${target}\n`;
          count++;
        }
        md += "```\n\n";
      }
    }
  } else {
    md += `## Violations\n\nNone - page passes all automated checks.\n\n`;
  }

  md += `---\n*Generated by Phase 7 page-level verification infrastructure*\n`;

  return md;
}

/**
 * Generate a summary report across all audited pages.
 *
 * Creates an aggregate view with:
 * - Overall pass/fail count
 * - List of pages with their status
 * - List of pages with violations (if any)
 *
 * @param allResults - Map of page name to array of AuditResults
 * @returns Markdown string
 */
export function generateSummaryReport(
  allResults: Map<string, AuditResult[]>
): string {
  const totalPages = allResults.size;
  let passingPages = 0;
  let failingPages = 0;
  let totalViolations = 0;
  let totalCombinations = 0;

  const pageStatuses: Array<{
    name: string;
    url: string;
    status: "PASS" | "FAIL";
    violations: number;
    combinations: number;
  }> = [];

  for (const [pageName, results] of Array.from(allResults.entries())) {
    const pageStatus = results.every((r) => r.status === "PASS")
      ? "PASS"
      : "FAIL";
    const pageViolations = results.reduce(
      (sum, r) => sum + r.violations.length,
      0
    );

    if (pageStatus === "PASS") {
      passingPages++;
    } else {
      failingPages++;
    }

    totalViolations += pageViolations;
    totalCombinations += results.length;

    pageStatuses.push({
      name: pageName,
      url: results[0]?.url || "N/A",
      status: pageStatus,
      violations: pageViolations,
      combinations: results.length,
    });
  }

  // Build report
  let md = `# Page-Level Verification Summary\n\n`;
  md += `**Generated:** ${new Date().toISOString()}\n`;
  md += `**Overall Status:** ${failingPages === 0 ? "PASS" : "FAIL"}\n\n`;

  md += `## Overview\n\n`;
  md += `| Metric | Value |\n`;
  md += `|--------|-------|\n`;
  md += `| Total Pages | ${totalPages} |\n`;
  md += `| Passing Pages | ${passingPages} |\n`;
  md += `| Failing Pages | ${failingPages} |\n`;
  md += `| Total Combinations | ${totalCombinations} |\n`;
  md += `| Total Violations | ${totalViolations} |\n`;
  md += `| Pass Rate | ${((passingPages / totalPages) * 100).toFixed(1)}% |\n\n`;

  md += `## Page Status\n\n`;
  md += `| Page | URL | Status | Violations | Combinations |\n`;
  md += `|------|-----|--------|------------|---------------|\n`;

  // Sort by status (failing first) then by name
  pageStatuses.sort((a, b) => {
    if (a.status !== b.status) {
      return a.status === "FAIL" ? -1 : 1;
    }
    return a.name.localeCompare(b.name);
  });

  for (const page of pageStatuses) {
    md += `| ${page.name} | ${page.url} | ${page.status} | ${page.violations} | ${page.combinations} |\n`;
  }
  md += `\n`;

  // List failing pages with details
  const failingPagesList = pageStatuses.filter((p) => p.status === "FAIL");
  if (failingPagesList.length > 0) {
    md += `## Pages Requiring Attention\n\n`;
    for (const page of failingPagesList) {
      md += `- **${page.name}** (${page.url}): ${page.violations} violations\n`;
    }
    md += `\n`;
  }

  md += `---\n*Generated by Phase 7 page-level verification infrastructure*\n`;

  return md;
}

/**
 * Format a violation for console output (debugging).
 *
 * @param violation - Single AxeViolation
 * @returns Formatted string for console.log
 */
export function formatViolationForConsole(violation: AxeViolation): string {
  let output = `[${violation.impact?.toUpperCase() || "UNKNOWN"}] ${violation.id}: ${violation.help}\n`;

  for (const node of violation.nodes.slice(0, 3)) {
    output += `  - ${node.target.join(" > ")}\n`;
    if (node.failureSummary) {
      output += `    ${node.failureSummary.split("\n")[0]}\n`;
    }
  }

  if (violation.nodes.length > 3) {
    output += `  ... and ${violation.nodes.length - 3} more elements\n`;
  }

  return output;
}
