"use client";

import type { IconProps as PhosphorIconProps } from "@phosphor-icons/react";
import type { ComponentType } from "react";
import {
  ArrowClockwise,
  ArrowLeft,
  ArrowRight,
  ArrowSquareOut,
  ArrowUp,
  ArrowsClockwise,
  Briefcase,
  Bug,
  Calendar,
  CalendarCheck,
  CalendarX,
  Camera,
  CaretDown,
  CaretRight,
  ChartLineUp,
  Check,
  CheckCircle,
  CircleHalf,
  CircleNotch,
  Code,
  CopySimple,
  Download,
  DotsThree,
  DotsThreeVertical,
  DribbbleLogo,
  Eye,
  FacebookLogo,
  FileText,
  Folder,
  Gear,
  GithubLogo,
  Heart,
  House,
  Info,
  InstagramLogo,
  Lightning,
  LinkedinLogo,
  List,
  MagnifyingGlass,
  MediumLogo,
  Moon,
  Newspaper,
  NewspaperClipping,
  Palette,
  PaperPlaneTilt,
  Pencil,
  Plus,
  QuestionMark,
  Robot,
  SealCheck,
  ShareNetwork,
  SignOut,
  Star,
  Strategy,
  Sun,
  TextAlignLeft,
  User,
  Warning,
  WarningCircle,
  WhatsappLogo,
  Wrench,
  X,
  XCircle,
  XLogo,
  RedditLogo,
} from "@phosphor-icons/react/ssr";

export type PhosphorIconComponent = ComponentType<PhosphorIconProps>;

/** Curated Phosphor icons used by the design system (avoids importing the full icon set). */
const PHOSPHOR_ICONS = {
  ArrowClockwise,
  ArrowLeft,
  ArrowRight,
  ArrowSquareOut,
  ArrowUp,
  ArrowsClockwise,
  Briefcase,
  Bug,
  Calendar,
  CalendarCheck,
  CalendarX,
  Camera,
  CaretDown,
  CaretRight,
  ChartLineUp,
  Check,
  CheckCircle,
  CircleHalf,
  CircleNotch,
  Code,
  CopySimple,
  Download,
  DotsThree,
  DotsThreeVertical,
  DribbbleLogo,
  Eye,
  FacebookLogo,
  FileText,
  Folder,
  Gear,
  GithubLogo,
  Heart,
  House,
  Info,
  InstagramLogo,
  Lightning,
  LinkedinLogo,
  List,
  MagnifyingGlass,
  MediumLogo,
  Moon,
  Newspaper,
  NewspaperClipping,
  Palette,
  PaperPlaneTilt,
  Pencil,
  Plus,
  QuestionMark,
  Robot,
  SealCheck,
  ShareNetwork,
  SignOut,
  Star,
  Strategy,
  Sun,
  TextAlignLeft,
  User,
  Warning,
  WarningCircle,
  WhatsappLogo,
  Wrench,
  X,
  XCircle,
  XLogo,
  RedditLogo,
} as const satisfies Record<string, PhosphorIconComponent>;

/** Legacy FontAwesome-style slugs and kebab names → registry keys in PHOSPHOR_ICONS. */
export const ICON_ALIASES: Record<string, keyof typeof PHOSPHOR_ICONS> = {
  "circle-info": "Info",
  info: "Info",
  "circle-check": "CheckCircle",
  "check-circle": "CheckCircle",
  "circle-xmark": "XCircle",
  "x-circle": "XCircle",
  "triangle-exclamation": "WarningCircle",
  "warning-circle": "WarningCircle",
  warning: "Warning",
  "share-nodes": "ShareNetwork",
  "share-network": "ShareNetwork",
  copy: "CopySimple",
  "copy-simple": "CopySimple",
  sync: "ArrowsClockwise",
  "arrows-rotate": "ArrowsClockwise",
  "arrow-right": "ArrowRight",
  "arrow-left": "ArrowLeft",
  "arrow-up": "ArrowUp",
  "arrow-clockwise": "ArrowClockwise",
  arrowClockwise: "ArrowClockwise",
  github: "GithubLogo",
  "github-logo": "GithubLogo",
  "square-instagram": "InstagramLogo",
  instagram: "InstagramLogo",
  "instagram-logo": "InstagramLogo",
  "square-x-twitter": "XLogo",
  "x-twitter": "XLogo",
  "twitter-logo": "XLogo",
  "square-facebook": "FacebookLogo",
  facebook: "FacebookLogo",
  "facebook-logo": "FacebookLogo",
  "square-whatsapp": "WhatsappLogo",
  whatsapp: "WhatsappLogo",
  "whatsapp-logo": "WhatsappLogo",
  "reddit-alien": "RedditLogo",
  reddit: "RedditLogo",
  "reddit-logo": "RedditLogo",
  x: "X",
  "text-align-left": "TextAlignLeft",
  "newspaper-clipping": "NewspaperClipping",
  newspaper: "Newspaper",
  "linkedin-logo": "LinkedinLogo",
  "dribbble-logo": "DribbbleLogo",
  "medium-logo": "MediumLogo",
  "caret-down": "CaretDown",
  "caret-right": "CaretRight",
  "calendar-check": "CalendarCheck",
  "calendar-x": "CalendarX",
  "file-text": "FileText",
  "circle-half": "CircleHalf",
  "circle-notch": "CircleNotch",
  "arrow-square-out": "ArrowSquareOut",
  "dots-three": "DotsThree",
  "dots-three-vertical": "DotsThreeVertical",
  "paper-plane-tilt": "PaperPlaneTilt",
  plus: "Plus",
  "check-fat": "Check",
  "question-mark": "QuestionMark",
  "sign-out": "SignOut",
  "chart-line-up": "ChartLineUp",
  "seal-check": "SealCheck",
  magnifyingglass: "MagnifyingGlass",
  MagnifyingGlass: "MagnifyingGlass",
  close: "X",
  xmark: "X",
};

const toPascalCase = (value: string) =>
  value
    .split(/[\s_-]+/)
    .filter(Boolean)
    .map((segment) => segment[0].toUpperCase() + segment.slice(1))
    .join("");

export function resolvePhosphorIcon(
  rawName: string,
): PhosphorIconComponent | null {
  const cleaned = rawName?.replace(/^fa-/, "") ?? "";
  const alias =
    ICON_ALIASES[cleaned] ??
    ICON_ALIASES[rawName] ??
    ICON_ALIASES[toPascalCase(cleaned)];
  const candidates = [
    alias,
    toPascalCase(cleaned),
    cleaned,
    rawName,
  ].filter(Boolean) as string[];

  for (const candidate of candidates) {
    const direct = PHOSPHOR_ICONS[candidate as keyof typeof PHOSPHOR_ICONS];
    if (direct) return direct;

    const fromAlias = ICON_ALIASES[candidate];
    if (fromAlias) return PHOSPHOR_ICONS[fromAlias];
  }

  return null;
}
