name: PR Preview
on:
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write
concurrency:
  group: pages-preview-main
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/configure-pages@v5
      - run: npm ci
      - run: PUBLIC_URL=. npm run build
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    if: github.ref == 'refs/heads/main'
    steps:
      - id: deploy
        uses: actions/deploy-pages@v4
        with:
          preview: false
